name: Automated Release

on:
  push:
    tags:
      - 'v*.*.*'   
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build artifact (example)
        run: |
          mkdir dist
          echo "This is a release artifact." > dist/release-notes.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/release-notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
